### ISSUE TITLE
HttpInvocation.invoke() should support authentication

### ISSUE THREAD

**Issue by coodoo** [strongloop/strong-remoting#105]
When replicating local model with remote models, it will trigger REST end points on remote server, sometimes it would be necessary to pass TOKEN in the request header for authorization, it's not possible with current implementation.

Ideally, TOKEN should be passed down all the way from persisted-model when invoking, or better yet, token can be stored somewhere (probably app.settings{} or app.configs{}) for easier access.

Here's the pseudo code of how it works if TOKEN were passed down:

In http-invocation.js:
```js
HttpInvocation.prototype.invoke = function (callback) {
  var req = this.createRequest();
  
  // append TOKEN to req.headers, in this case, I storing it in window{} earlier, which of course is a hack
  req.headers = {'Authorization': window.zoken};

  request(req, function(err, res, body) {
    if(err instanceof SyntaxError) {
      if(res.status === 204) err = null;
    }
    if(err) return callback(err);
    this.transformResponse(res, body, callback);
  }.bind(this));
}
```

PS. just reviewed the whole replication/diff/merge implementation, really great work, two thumbs up! Can't wait to use it in my next project.

**Comment by bajtos** [comment]
Related? strongloop/loopback-connector-remote#11

**Comment by ritch** [comment]
`remotes.auth` released as **2.13.0**

**Comment by bajtos** [comment]
Here is a code snippet showing how to set the access token in a loopback application, assuming that the data-source backed by the remote connector is called "remote":

    app.dataSources.remote.connector.remotes.auth = {
      bearer: new Buffer(token).toString('base64'),
      sendImmediately: true
    };

@ritch I find this rather difficult to use, it took me quite a lot of debugging to find out where exactly the token should be set. I think we should add some sugar API to make this easier.

@crandmck Is there any documentation explaining how to configure the remoting connector? I'd like to include this information there.

**Comment by bajtos** [comment]
Let's follow up here: https://github.com/strongloop/loopback-connector-remote/issues/3

**Comment by crandmck** [comment]
@bajtos Here is the doc for the remote connector: http://docs.strongloop.com/display/LB/Remote+connector  Feel free to add something there until https://github.com/strongloop/loopback-connector-remote/issues/3 is resolved.

**Comment by bajtos** [comment]
@crandmck done, I have added a new section named "Configuring authentication". Feel free to improve the content as you wish.

**Comment by crandmck** [comment]
Thanks. LGTM.
