### ISSUE TITLE
Default Chrome/Firefox Accepts header forces an xml response when a json response was expected

### ISSUE THREAD

**Issue by gcirne** [strongloop/strong-remoting#118]
I have an API built with Loopback which only supports json responses.

If I access my API using Chrome, its default Accepts header (text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8) forces an xml response to be returned. This was introduced by commit 066e9bdf5fe95395296129b1e6e51f2b0b41de56.

Is there some way where I can configure which types my API supports?

**Comment by Rezakhatami** [comment]
very nice

**Comment by wangpengfei15975** [comment]
thx
