### ISSUE TITLE
Move adapters to standalone packages

### ISSUE THREAD

**Issue by bajtos** [strongloop/strong-remoting#141]
- Implement a mechanism allowing strong-remoting users to provide their own transport/adapter implementations.
- Move all adapters except REST to standalone packages, e.g. strong-remoting-jsonrpc, strong-remoting-socketio, etc.

Benefits:
- Boost for innovations. Users can implement a custom adapter in their own module, they don't have to wait until it is landed in strong-remoting core.
- Fine grained project permissions - we can grant committer bits on per-adapter basis.
- Applications using REST transport only don't need build tools to install, as the only native dependency `ws` will be moved to the socketio adapter.

**Comment by richardpringle** [comment]
@bajtos, is this still happening?

**Comment by bajtos** [comment]
I am afraid this is not a priority right now. I'll remove it from LB 3.0 milestone.

**Comment by deepakrkris** [comment]
@bajtos self-assigned this to me. lets discuss on the next steps

**Comment by bajtos** [comment]
@deepakrkris I am afraid I don't have enough bandwidth to look into this right now. Considering that all non-REST adapters are way behind the REST adapter in the terms of feature parity, I am proposing to simply remove all non-REST adapters in the `master` branch (the upcoming 3.0 release). Then we can wait for user feedback to see if anybody complains about a missing adapter in 3.0.

I think we can use this GH issue to keep track of those complaints/requests, just mention it in the release notes entry (see https://github.com/strongloop/loopback/blob/5fd1766a8160b830a3091a83d8d24210178699db/3.0-DEVELOPING.md#keeping-track-of-major-and-breaking-changes).

**Comment by ritch** [comment]
Lets close this. I don't think we'll ever get to it.
