### ISSUE TITLE
Allow remote methods to be classified as 'READ' or 'WRITE'

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/strong-remoting#146]
LoopBack hard codes the mapping of CRUD methods to READ/WRITE at https://github.com/strongloop/loopback/blob/master/lib/model.js#L306. It doesn't work for custom methods, see https://github.com/strongloop/loopback-component-storage/issues/10#issuecomment-66132814.

I propose that we allow developers to declare `accessType` for shared methods, such as,

UserModel.remoteMethod(
      'resetPassword',
      {
        description: 'Reset password for a user with email',
        accepts: [
          {arg: 'options', type: 'object', required: true, http: {source: 'body'}}
        ],
        http: {verb: 'post', path: '/reset'},
        accessType: 'WRITE'
      }
    );

And enhance https://github.com/strongloop/loopback/blob/master/lib/model.js#L306 to check the accessType of the shared method.

**Comment by ritch** [comment]
This is merged.
