### ISSUE TITLE
Remote Connector Does not call execHooks on invoke

### ISSUE THREAD

**Issue by BerkeleyTrue** [strongloop/strong-remoting#150]
Is there a specific reason why the [RestAdapter.prototype.invoke](https://github.com/strongloop/strong-remoting/blob/master/lib/rest-adapter.js#L100) method does not call execHooks? 

I am extending loopback-connector-remote to hook into user.login/logout and these do not get called due to the above. 

I would be glad to submit a PR if there is not specific reason.

**Comment by bajtos** [comment]
@BerkeleyTrue is this fixed now that #152 was landed?

**Comment by BerkeleyTrue** [comment]
@bajtos Yes. Closing.
