### ISSUE TITLE
express 4.11.0 deprecated req.param()

### ISSUE THREAD

**Issue by aars** [strongloop/strong-remoting#158]
Submitting patch.

**Comment by bajtos** [comment]
Hi @aars, thank you for the patch. Please send it as a pull request, you can learn more about GitHub pull requests in their [docs](https://help.github.com/articles/using-pull-requests/).

Also please reword the commit message to follow the [50/72 rule](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html). Use imperative tense ("Remove use of ...") and don't include the issue number in the summary line. It is not necessary to include the issue number in the commit at all, the link will be recorded in the merge commit.

**Comment by bajtos** [comment]
Never mind, I can see that you have already submitted the patch in #159. Next time, it's enough to send a pull request, there is no need to create another issue.

**Comment by aars** [comment]
Ah yeah. I misread this part "Create a GitHub issue for large changes and discuss the change there before coding. You can skip this step and submit the pull request for minor changes."

This is not a large change :)

I will also mind the tense of the commit messages, this style of messages was recently forced upon me and I'm still used to it.

**Comment by bajtos** [comment]
> I will also mind the tense of the commit messages, this style of messages was recently forced upon me and I'm still used to it.

Yeah, I totally understand that, I used to be used to past tense for many years and it took me several months to eventually adapt to the new style.
