### ISSUE TITLE
Use of deprecated req.param() from express in HttpContext#getArgByName

### ISSUE THREAD

**Issue by sethetter** [strongloop/strong-remoting#170]
This issue came up came up while using [loopback-testing](https://github.com/strongloop/loopback-testing) and noticed deprecation warnings from express about `req.param()`. Here are the [offending](https://github.com/strongloop/strong-remoting/blob/master/lib/http-context.js#L142) [lines](https://github.com/strongloop/strong-remoting/blob/master/lib/http-context.js#L153).

**Comment by bajtos** [comment]
Fixed by #171
