### ISSUE TITLE
Browser-Request doesn't work in most browsers

### ISSUE THREAD

**Issue by bitmage** [strongloop/strong-remoting#177]
One of your dependencies, [browser-request](https://github.com/iriscouch/browser-request/), seems to have fallen out of maintenance.  There's a number of [pull requests with no responses](https://github.com/iriscouch/browser-request/pulls) and the library hasn't had any activity in the last year.

[Browser support is poor](https://ci.testling.com/maxogden/browser-request).  I'm not even sure if these results are accurate, since they're attached to a fork that maxogden wrote at some point.  But they're linked to from the README on the main branch.

Since strong-remoting is what client-side loopback models will use to communicate with the server side API, it seems pretty crucial that this work cross browser.

It seems like the only place we are referencing browser-request is [in the package.json](https://github.com/strongloop/strong-remoting/blob/master/package.json#L66).  I think this section is being interpreted by browserify?  Would it be possible to just use the http API and let browserify [handle it natively](https://github.com/substack/http-browserify)?  The browserify module says it's [tested and working in most relevant browsers](https://github.com/substack/http-browserify#compatibility).

**Comment by ritch** [comment]
> Since strong-remoting is what client-side loopback models will use to communicate with the server side API, it seems pretty crucial that this work cross browser.

Agreed.

> It seems like the only place we are referencing browser-request is in the package.json. 

Basically yes.

> Would it be possible to just use the http API and let browserify handle it natively? The browserify module says it's tested and working in most relevant browsers.

This might require some changes to `request`. It is worth looking into though. I would love to drop the `browser-request` dependency.

**Comment by bajtos** [comment]
@ritch Is it important to implement this change for our sync v1.0 milestone? If it is, then please assign it to the milestone.

**Comment by bajtos** [comment]
One more problem of the current implementation: http-browserify has about 15kb and it requires readable-stream, which adds another 55kb to the browser bundle size.

Ideally, the remote connector should use an API that is closer to browser's XHR, so that the code overhead is as small as possible.

**Comment by ritch** [comment]
I'd like to fix this with https://github.com/strongloop/strong-remoting/issues/177 @bitmage can you comment there?

**Comment by ritch** [comment]
We are not longer using `browser-request`...
