### ISSUE TITLE
Browser: Support partial URLs 

### ISSUE THREAD

**Issue by ritch** [strongloop/strong-remoting#200]
When we `remotes.connect()` to `/api` and we are in the browser, remoting should be smart enough to build the full URL from `window.location.origin` or similar.

**Comment by BerkeleyTrue** [comment]
:+1:

**Comment by ritch** [comment]
I think this is a limitation of `request`.

**Comment by richardpringle** [comment]
Still doing a little old issue cleanup. I believe that this can be closed. Please re-open and mention me directly if need be.
