### ISSUE TITLE
How can download a csv in a remote method?

### ISSUE THREAD

**Issue by Karabi-Choudhury** [strongloop/strong-remoting#206]
Hi,

I have written a remote method which is doing find based on filter as input. I want the the results of the find to be downloaded to csv in the browser once the user make a call to the api. How can i do it?

**Comment by bajtos** [comment]
I would recommend to implement an "after" hook that will send a custom response in CSV format using the result of the function.

Below is a sample code to illustrate the idea, note that I did not test it myself.

```js
MyClass.mymethod = function(cb) {
  var rows = [
     ['id', 'name'],
     [1, 'Alice'],
     [2, 'Bob']
  ];
  cb(null, rows);
});

MyClass.after('mymethod', function(ctx, next) {
  // FIXME: use a proper CSV formatter that can escape string values containing "," characters
  var csv = ctx.result.rows.map(function(r) { return r.join(','); }).join('\n');
  ctx.res.header('Content-Type', 'text/csv');
  ctx.res.send(csv);
  // next() must not be called!
});
```

**Comment by Karabi-Choudhury** [comment]
Can i make it a get request

**Comment by bajtos** [comment]
> Can i make it a get request

Sure, see "http.path" in [docs](http://docs.strongloop.com/display/LB/Remote+methods#Remotemethods-Options).

**Comment by Karabi-Choudhury** [comment]
Thanks a lot

**Comment by bajtos** [comment]
I am closing the issue as resolved/answered. Please post any further questions to [our mailing list](https://groups.google.com/forum/#!forum/loopbackjs).

**Comment by Karabi-Choudhury** [comment]
The file that i get doesn't have .csv extension.How can i enable that?
