### ISSUE TITLE
Support Date strings in `isAcceptable()`

### ISSUE THREAD

**Issue by ritch** [strongloop/strong-remoting#211]
https://github.com/strongloop/strong-remoting/blob/c7cb7c5e827f2cc96e55bcfbbef19793a0dbabfa/lib/http-invocation.js#L80

Won't allow you to pass a `String` when it expects a `Date`.

/cc @anthonyettinger 

Should we allow strings as well (since they will be coerced on the other side)? Right now the behavior is that we just omit the parameter which is confusing.

**Comment by richardpringle** [comment]
This hasn't been touched in a year. I assume it has either been dealt with or is no longer a concern. If the issue persists I'm going to say we should open a new issue since the context is probably a lot different than a year ago.
