### ISSUE TITLE
Primus Adapter

### ISSUE THREAD

**Issue by ritch** [strongloop/strong-remoting#215]
I'd like to be able to invoke remote methods using primus as the transport.

This adapter should support creating `ReadableStream`s on the server and consuming them on the client.

**Comment by pierissimo** [comment]
I've done an initial implementation [here](https://github.com/strongloop/strong-remoting/pull/405).
A few parts are not/partially implemented.
Please review it and let me know how it can be improved.

**Comment by bajtos** [comment]
Closing in favour of a community-maintained Primus component: https://github.com/Oneflow/loopback-component-primus

Thank you @pierissimo for making this happen! ❤️

**Comment by pierissimo** [comment]
@bajtos thank you for your help!
