### ISSUE TITLE
Unable to accept XML data through a remote method

### ISSUE THREAD

**Issue by mrfelton** [strongloop/strong-remoting#224]
I'm trying to create a remote method that accepts XML data in the POST body. However, after defining the arg I don't seem to be getting the data through to my method.

The arg is defined like:

```json
 {
        "arg": "payload",
        "type": "String",
        "required": true,
        "description": "Webhook payload.",
        "http": {
          "source": "body"
        }
  }
```

However, what I seem to be getting through to the remote method is a string with the content "[object Object]"

I am setting the content type header as `Content-Type: application/xml; charset=utf-8` but it does not appear to be honouring that.

I think this may be related to https://github.com/strongloop/strong-remoting/blob/e76c1a7ce56d86beceb8ed3d8d54fa30ac83bafa/lib/http-context.js#L154 where it looks like you try and coerce the data to json.

**Comment by mrfelton** [comment]
By adding https://github.com/macedigital/express-xml-bodyparser as middleware in middleware.json I have been ale to make the xml body data available in my remote method, but only by accessing it directly  as in:

```javascript
var loopbackContext = loopback.getCurrentContext();
var http = loopbackContext ? loopbackContext.get('http') : null;
var req = http ? http.req : null;
data - req.body;
```

It still doesn't make it's way through as an argument to the remote method.

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/strong-remoting/blob/master/test/rest.test.js#L233-L273 <https://github.com/strongloop/strong-remoting/blob/master/test/rest.test.js#L233-L273>

Thanks,

---
Raymond Feng
Co-Founder and Architect @ StrongLoop, Inc.

StrongLoop <http://strongloop.com/> makes it easy to develop APIs <http://strongloop.com/mobile-application-development/loopback/> in Node, plus get DevOps capabilities <http://strongloop.com/node-js-performance/strongops/> like monitoring, debugging and clustering.

**Comment by mrfelton** [comment]
I understand that you can make it respond with XML data like that, but what I'm looking to do is receive XML data through an argument in `accepts`. My methods doesn't return anything. This is so that I can receive incoming XML data and process it.

**Comment by cnaccio** [comment]
I'm having this same problem. @mrfelton did you ever get this working? We're swapping out a legacy API with Strongloop/Loopback, and we're trying to avoid having to update any client code. Any help would be much appreciated. Thanks!

**Comment by pulkitsinghal** [comment]
@raymondfeng - any updated thoughts on @mrfelton's last comment?

**Comment by pulkitsinghal** [comment]
@mrfelton - after adding:
```
  "parse": {
    "express-xml-bodyparser": {
      "params": {
        "normalize": true,
        "normalizeTags": false,
        "explicitArray": false
      }
    }
  },
```
to `middleware.json` ... I do get XML converted to JSON coming through via an argument: `{arg: 'data', required: true, type: 'object', http: { source: 'body' }}` ... is that what you too noticed or is it just a bit different from what you were stating back then?

**Comment by mrfelton** [comment]
@pulkitsinghal yes, thats essentially what I did in middleware.json, but from memory I wasn't able to get that data coming through as an argument as defined in the model schema. I ended up pulling it out of `http.req`. Interesting to know that you have it working. I'll revisit our code at some point and see I can do the same.

**Comment by glesage** [comment]
Hey all, have you been able to get this to work by any chance?

**Comment by pulkitsinghal** [comment]
@glesage - yes got it to work with the changes outlined in my previous comment

**Comment by glesage** [comment]
Any ideas if the

**Comment by jbcpollak** [comment]
I'm having the same problem, but with non-XML data (in my case CSV data, but it should support anything). In short, I would expect that a remote method definition like this:

```
 {
        "arg": "payload",
        "type": "String",
        "required": true,
        "description": "Webhook payload.",
        "http": {
          "source": "body"
        }
  }
```

would pass the raw body to the remote method. But instead there seems to be something interfering with the processing of the body, and there should be a (documented) way of disabling it.

**Comment by richardpringle** [comment]
Hey guys, from following the comments... it looks like this issue has been "resolved" with a workaround. It also looks to me like there is a feature request here for an easier way to do this. Could someone open a new feature request that clearly defines the objective? I think it could be pretty useful for a lot of users.

cc/ @mrfelton @pulkitsinghal @jbcpollak

**Comment by joetinoco** [comment]
@jbcpollak You probably already figured it out, but I'd like to post a solution to non-XML data parsing, just in case someone else is struggling with this.

Just install BodyParser with `npm install body-parser --save` and add this to `middleware.json`:

```
"parse": {
    "body-parser#text": {"params": { "limit": "1024kb" }}
  }
```
`limit` can be changed to whatever you need.

Note that this only works if the `Content-Type` in the request header is set to `text/plain`. The API explorer won't allow it so you'll have to use CURL or Postman or other tool.

I got the `middleware.json` configs from [this SO answer](http://stackoverflow.com/a/28530509/4838167).

**Comment by richardpringle** [comment]
Thanks @joetinoco!

**Comment by richardpringle** [comment]
Closing this issue as it looks like it is solved. 

The answer being, use a "body parsing" middleware module from npm (or create your own) and register it in the middlerware.json file. 

If anyone feels that this issue, please re-open the issue and mention me in a comment and I will try to make sure we get this thing solved.

**Comment by guneraykut** [comment]
@richardpringle how about parsing xml data through the built-in remote method. I asked this at https://github.com/strongloop/strong-remoting/issues/461

**Comment by richardpringle** [comment]
Sorry @guneraykut, I'm no longer a maintainer of this project, hopefully someone responds on your issue soon though!
