### ISSUE TITLE
remoteObjects.invoke() destroys `included` related models

### ISSUE THREAD

**Issue by simoami** [strongloop/strong-remoting#228]
I just discovered that if you invoke a rest method with remoteObjects.invoke(), the included related models are stripped. This is a side effect of converting the returned json into a model instance in HttpInvocation logic. 

1. A request is created and the response is transformed:
```
HttpInvocation.prototype.invoke = function(callback) {
  ...
  request(this.req, function(err, res, body) {
   ...
    self.transformResponse(res, body, callback); // <<<----- HERE
  });
};
model = new PersistedModel(res.body); 
``` 

2. The transformer then converts json response into a model instance:
```
HttpInvocation.prototype.transformResponse = function(res, body, callback) {
  var callbackArgs = [null]; // null => placeholder for err
  val = res.body;
  ...
  dynamic = new Dynamic(val, ctx);
  val = dynamic.to(type); <<< ------ Conversion happens HERE
  ...
  callbackArgs.push(val);

  callback.apply(this, callbackArgs);
};

```

3. Dynamic converts the dynamic value to the given type:
```
Dynamic.prototype.to = function(type) {
  var converter = this.constructor.getConverter(type);
  return converter(this.val, this.ctx); <<< ------ Conversion happens HERE
};
```

4. This model converter is called:
```
// setup a remoting type converter for this model
    RemoteObjects.convert(typeName, function(val) {
      return val ? new ModelCtor(val) : val; <<< ----- the included property is finally LOST here
    });
```

Demonstration:

![includes_filter_issue](https://cloud.githubusercontent.com/assets/2038264/8883676/9967b29c-321e-11e5-8a70-388a49523bff.gif)

**Comment by raymondfeng** [comment]
The included object is not a regular property of the model. The constructor probably should pass in a flag to ensure schema-less conversion.

**Comment by simoami** [comment]
I used RemoteObjects.invoke() because it was the only way I could run acl and before / after hooks for a given method. Any other ways you'd suggest?

**Comment by raymondfeng** [comment]
Model.checkAccess() has the logic to trigger ACLs.

**Comment by simoami** [comment]
hmm, I considered that path a week ago. if I am to do to recode the whole logic for orchestrating calls (checkACL, call before hooks, call after hooks...) , my implementation could become vulnerable to future updates.

I see that the Model constructor has a strict property, which could potentially be used for retaining related properties.

what do you think?

**Comment by simoami** [comment]
or even better, skip model transformation or keep sourceJSON in the model, like `__sourceData`.

**Comment by simoami** [comment]
Update: I see that the relations are not exactly lost. They're being stored in model.__cachedRelations.

I think I'd just merge that with __data into a new json object.

**Comment by richardpringle** [comment]
@simoami Looks like you solved the issue. Anyway, I think if any related issues come up they should go to [LoopBack](https://github.com/strongloop/loopback) since it involves both the Model Class as well as strong-remoting.

**Comment by simoami** [comment]
@richardpringle I did not solve the issue. I just helped figure this out and offering ways to solve it.

**Comment by richardpringle** [comment]
@simoami, sorry to hear that it didn't get completely solved. As I said, better to open in LoopBack next time. Can always mention me directly to try and get the issue solved a little faster too.
