### ISSUE TITLE
Method not invoked from file based html application

### ISSUE THREAD

**Issue by ritch** [strongloop/strong-remoting#229]
<img width="1268" alt="screen shot 2015-07-30 at 2 39 13 pm" src="https://cloud.githubusercontent.com/assets/462228/8995899/49ec3f44-36c9-11e5-8ee0-dfb3a9c43808.png">
It looks like no HTTP requests are made when running within a file based app (eg. cordova).

**Comment by OpenSystemsConsulting** [comment]
Ping
