### ISSUE TITLE
Add route based lookup API

### ISSUE THREAD

**Issue by ritch** [strongloop/strong-remoting#246]
This would make it easier for us to support configurations that take an API or route as input instead of an exact `SharedMethod` name. Below are some basic examples

``` js
var methods = remotes.findByRoute('get', '/todos');
console.log(methods[0].name); // => find
```

``` js
// glob supported
var methods = remotes.findByRoute('get', '**');
// => all GET methods

var methods = remotes.findByRoute('get', '/*/*/count');
// => all count methods
```

**Comment by raymondfeng** [comment]
Nice

**Comment by fabien** [comment]
:+1:

**Comment by bajtos** [comment]
Cool :+1:

**Comment by richardpringle** [comment]
+1

**Comment by bajtos** [comment]
With the release of LoopBack 4.0 GA (see the [announcement](https://strongloop.com/strongblog/loopback-4-ga)), this module has entered Active LTS mode and no longer accepts new features (see our [LTS policy](https://loopback.io/doc/en/contrib/Long-term-support.html)).
