### ISSUE TITLE
Last Update for Accept "application/vnd.api+json" Breaks Apps[Urgent]

### ISSUE THREAD

**Issue by jaime-franco** [strongloop/strong-remoting#251]
Responses now are default "application/vnd.api+json", in the case in the file  lib/http-context.js is the returned when accepts is */*.

https://github.com/strongloop/strong-remoting/commit/d7d9a73cc77f33c13f31d3c8e57af8277e33363c

**Comment by jaime-franco** [comment]
If some one has the same problem you can add in the config file

    "rest": {
      "supportedTypes": [ "application/json"]
    }

But it will be great if the default setting is json instead of vnd.api+json

**Comment by voitau** [comment]
Could someone from Strongloop confirm that the fix suggested by @jaime-franco is a proper fix/workaround? Thanks!

**Comment by jaime-franco** [comment]
Hi, @voitau  i found the config information on this link :

https://docs.strongloop.com/display/public/LB/config.json#config.json-Remotingproperties

And i think this is a issue because in the documentation you can read : 

NOTE: 'application/vnd.api+json' is supported, but is not one of the default types. 

And actually this las update change that.

**Comment by raymondfeng** [comment]
Can you submit a patch so that `case '*/*':` goes with `case 'json':`?

**Comment by jaime-franco** [comment]
Ok

**Comment by voitau** [comment]
Thanks for a quick fix! Is there a release with this fix planned?
