### ISSUE TITLE
objectId will be parsed to integer if it only contains digit

### ISSUE THREAD

**Issue by clarkorz** [strongloop/strong-remoting#253]
e.g.: `GET /api/books/564196793878943870271416` will call `Book.findById()`, but the `id` argument has already been coerce to an integer.

This will cause a 404 error.

**Comment by clarkorz** [comment]
I think this [line](https://github.com/strongloop/strong-remoting/blob/master/lib/http-context.js#L293) is related.

But I don't have a proper way to fix this. Any idea?

**Comment by raymondfeng** [comment]
I have a pending PR that fixes the problem but it breaks some tests in loopback-connector-remote. See https://github.com/strongloop/loopback/pull/1221.

**Comment by clarkorz** [comment]
ok, duplicate. close. see https://github.com/strongloop/loopback/issues/1217
