### ISSUE TITLE
Incorrect content type in 204 responses (expected XML)

### ISSUE THREAD

**Issue by bajtos** [strongloop/strong-remoting#258]
At the moment, we always return the content header as JSON when there isn't any response payload, even if the XML output is enabled and the client requested it.

**Comment by pulkitsinghal** [comment]
Where is it in https://waffle.io/strongloop/loopback?

**Comment by bajtos** [comment]
> Where is it in https://waffle.io/strongloop/loopback?

@pulkitsinghal This issue is sitting in the `Top of Backlog` column, which is our list of candidates to be planned for the next sprint.

**Comment by bajtos** [comment]
> At the moment, we always return the content header as JSON when there isn't any response payload, even if the XML output is enabled and the client requested it.

I have released the fix in `strong-remoting@2.23.2`.

@pulkitsinghal enjoy :)
