### ISSUE TITLE
Application/json body request with an extended content-type header (charset) should not be coerced

### ISSUE THREAD

**Issue by ebourmalo** [strongloop/strong-remoting#267]
The initial check to turn off the coercion of the request body when the header is `application/json` was:
```javascript
ctx.req.get('content-type') === 'application/json'
```

If the `content-type` header is extended with the charset definition (i.e `application/json;charset=UTF-8`), the body is coerced and that is NOT what we want :)

Here is the PR for a fix, updating the check for allowing this use case: https://github.com/strongloop/strong-remoting/pull/266

**Comment by STRML** [comment]
This is also fixed in #264.
