### ISSUE TITLE
Update Strong-remoting API docs for promises

### ISSUE THREAD

**Issue by davidcheung** [strongloop/strong-remoting#276]
Parent: strongloop/loopback/issues/1409
Related: strongloop-internal/strong-docs/issues/63, strongloop-internal/scrum-loopback/issues/615

`lib/remote-objects.js`
[RemoteObjects.after](https://apidocs.strongloop.com/strong-remoting/#remoteobjects-prototype-after)
[RemoteObjects.before](https://apidocs.strongloop.com/strong-remoting/#remoteobjects-prototype-before)

`lib/shared-method.js`
[sharedMethod.invoke](https://apidocs.strongloop.com/strong-remoting/#sharedmethod-prototype-invoke)

**Comment by bajtos** [comment]
@davidcheung @jannyHou  this is still relevant, although possibly in a different way than was originally meant.

> RemoteObjects.after
> RemoteObjects.before

These two methods accept an async handler function that is called for every request. This handler function signal the completion either by accepting a callback argument, as is currently shown in our API docs; or it can return a promise.

```js
// current example
remotes.after('dog.prototype.speak', function(ctx, next) {
  console.log('After speak!');
  next();
});

// promise version
remotes.after('dog.prototype.speak', function(ctx) {
  console.log('After speak!');
  return Promise.resolve();
});
```

> sharedMethod.invoke

This is an internal method that intentionally does not support Promise mode, there is no need to change the current API docs (IMO).

**Comment by jannyHou** [comment]
@bajtos Thank you for confirming, Makes sense now.
I am closing this issue since doc is not needed.

**Comment by bajtos** [comment]
@jannyHou I think it still makes sense to improve the doc and show how to write a handler function returning a promise.

```js
remotes.before('dog.prototype.speak', function(ctx) {
  console.log('Before speak!');
  return Promise.resolve();
});

remotes.after('dog.prototype.speak', function(ctx) {
  console.log('After speak!');
  return Promise.resolve();
});
```

**Comment by jannyHou** [comment]
oh ok lol @bajtos I will update the doc then. just keep the APIs doc as before.

**Comment by dhmlau** [comment]
Closing as resolved
