### ISSUE TITLE
Prototype methods apply ACL checks only after a model instance is found.

### ISSUE THREAD

**Issue by richardpringle** [strongloop/strong-remoting#311]
When making a call to `VERB api/ExampleModel/:id/operation` the ACL is only checked upon model instance discovery, otherwise you get a 404 response instead of a 401. This indicates that a record with that particular `id` does not exist even if the user does not have permission to check whether particular models exists or not.

**Comment by bajtos** [comment]
Cross posting @michaelfreund's  https://github.com/strongloop/loopback/issues/2398#issuecomment-224303992

> it is an information leak, where model ids can be iterated to check for model existence. this might be necessary information for further attack.

**Comment by bajtos** [comment]
@michaelfreund  @zkuang @richardpringle I have submitted to alternative pull requests to fix this issue, see #315 and #316. We are discussing with @ritch what would be the best fix, our concern is backwards compatibility. Feel free to try those patches out in your app and/or leave a comment what do you think.

**Comment by bajtos** [comment]
The fix is available in `strong-remoting@2.28.1`.

**Comment by michaelfreund** [comment]
@bajtos we can confirm this fixes #2220 for us.

**Comment by zkuang** [comment]
@bajtos sorry for the late reply. I'll check them out. Thanks very much.
