### ISSUE TITLE
[bug] can not identify the undefiend/null value of the boolean type argument.

### ISSUE THREAD

**Issue by snowyu** [strongloop/strong-remoting#322]
It always be converted false. It should not narrow it.

lib/dynamic.js:

```js
Dynamic.define('boolean', function convertBoolean(val) {
  switch (typeof val) {
    case 'string':
      switch (val) {
        case 'false':
        case 'undefined':
        case 'null':
        case '0':
        case '':
          return false;
        default:
          return true;
      }
      break;
    case 'number':
      return val !== 0;
    default:
      return Boolean(val);
  }
});
```

Correction:

```js
Dynamic.define('boolean', function convertBoolean(val) {
  switch (typeof val) {
    case 'string':
      switch (val.trim().toLowerCase()) {
        case 'false':
        case '0':
        case '':
          return false;
        case 'undefined': return undefined;
        case 'null': return null; //others still convert the null to false!! why??
        default:
          return true;
      }
      break;
    case 'number':
      return val !== 0;
    default:
      if (val !== null and val !== void 0)
        val = Boolean(val);
     return val;
  }
});
```

**Comment by richardpringle** [comment]
@snowyu, I'm not quite sure if I understand what you are trying to accomplish here.

`null` and `undefined` are both falsey values in JavaScript and thus should be coerced to `false`.

**Comment by snowyu** [comment]
Ok, eg, the `isInherited` is an optional boolean argument. 
The remote method need know the `isInherited` value whether the client be set or not.
But this force the value always is false.

* undefined: use the default value in the database.
* true: force to true.
* false: force to false.

**Comment by richardpringle** [comment]
A boolean is either `true` or ` false`.  A value of type "boolean" should never be null or undefined.

**Comment by richardpringle** [comment]
@snowyu, strong-remoting type coercion has been overhauled. I don't believe that this is still an issue. I'm going to close now but if you still believe that the bug is there, please feel free to re-open and leave a comment.

**Comment by snowyu** [comment]
Yes, I am sure it is a bug here. This is about the beautiful API design. NOT strict language design.

Without this, you haveto split one API method to TWO.  Why do not u think this is a js or sql bug too?

**Comment by richardpringle** [comment]
@snowyu, have you seen the new code https://github.com/strongloop/strong-remoting/blob/master/lib/types/boolean.js?

**Comment by snowyu** [comment]
Ok , I've seen the `undefined` value supported. in the new code
