### ISSUE TITLE
Infinite recursion for JSON object with circular refs

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/strong-remoting#34]
If the argument http source is 'req', it runs into an infinite recursion for the code at https://github.com/strongloop/strong-remoting/blob/master/lib/shared-method.js#L199.

**Comment by ritch** [comment]
This should be fixed now... I'm pretty sure @kraman is using this.

**Comment by kraman** [comment]
/cc @ritch @raymondfeng  
I am using `accepts: {arg: 'ctx', http: {source: 'context'}}`, Haven't used `req` source.
