### ISSUE TITLE
Regex support for remote hooks declarations

### ISSUE THREAD

**Issue by superkhau** [strongloop/strong-remoting#340]
As an end user, I would like to use regular expressions to match multiple remote methods.

For example:

```
module.exports = function(Payment) {
  Payment.helloRemote = function(msg, cb) {
    cb(null, 'hello');
  };
  Payment.remoteMethod('helloRemote', {
    accepts: {arg: 'msg', type: 'string'},
    returns: {arg: 'greeting', type: 'string'}
  });

  Payment.worldRemote = function(msg, cb) {
    cb(null, 'world');
  };
  Payment.remoteMethod('worldRemote', {
    accepts: {arg: 'msg', type: 'string'},
    returns: {arg: 'greeting', type: 'string'}
  });

  Payment.afterRemote('*Remote', function(ctx, user, next) {
    console.log('wildcard triggered');
    next();
  });
};
```

The current workaround is to use `ctx.method.name` to check if the remote method needs triggering:

```
Payment.afterRemote('*', function(ctx, user, next) {
  var ignoreList = ['helloRemote', 'worldRemote'];
  if (ignoreList.indexOf(ctx.method.name)) return next();

  // do something
  next();
});
```

**Comment by superkhau** [comment]
@bajtos This is probably just be a one off case for a customer request and I believe the workaround should be good enough for now. Feel free to plan accordingly as you see fit as this is probably a good feature to have in general.

**Comment by bajtos** [comment]
With the release of LoopBack 4.0 GA (see the [announcement](https://strongloop.com/strongblog/loopback-4-ga)), this module has entered Active LTS mode and no longer accepts new features (see our [LTS policy](https://loopback.io/doc/en/contrib/Long-term-support.html)).
