### ISSUE TITLE
Empty request body coerces to an empty object.

### ISSUE THREAD

**Issue by richardpringle** [strongloop/strong-remoting#342]
```shell
curl -i -X POST --header "Content-Type: application/json" --header "Accept: application/json"  "http://localhost:3000/api/Authors"
```
Creates a new Author record even though the request body is empty. It should at least require an empty object.

**Comment by richardpringle** [comment]
@bajtos, is this is expected behavior, please just close this issue

**Comment by bajtos** [comment]
To be honest, I don't know what's the expected behavior here. AFAICT, no real user complained about this so far, in which case I think it does not matter how we treat requests like these.
