### ISSUE TITLE
Stream as an accepts/returns argument

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/strong-remoting#35]
I'm trying to implement a 'download' remote method that will pipe a stream into http response. For example,

function download(..., cb) {
     var in = fs.createReadStream('1.jpg', ...);
     in.pipe(res);
}

There are a few options:

1. Have the download function to callback with a ReadStream so that strong-remoting will pipe it into the response.

2. Invent a way to declare req/res parameters so that strong-remoting can inject them for the method invocation.

3. Make HTTP context accessible by calling Context.getCurrent().

**Comment by bajtos** [comment]
As of #218, each "returns" argument can be configured to modify response status code or response header.

**Comment by bajtos** [comment]
When implementing this feature, we should take into account swagger type "file". It would be nice if the implementation in strong-remoting allowed us to support files in loopback-explorer. See https://github.com/strongloop/loopback-explorer/issues/103

**Comment by bajtos** [comment]
Closing as a duplicate of https://github.com/strongloop/loopback/issues/213.
