### ISSUE TITLE
Minor formatting issue of Error message

### ISSUE THREAD

**Issue by fabien** [strongloop/strong-remoting#373]
https://github.com/strongloop/strong-remoting/blob/14a03ccfd9a9b4210d3e68e9a87ed76e07948b6e/lib/rest-adapter.js#L329

```
{{Shared class}}  \"%s\" has no method handling %s %s
```

There are two spaces after `{{Shared class}}`.

**Comment by dhmlau** [comment]
Closing as PR #455 has landed.
