### ISSUE TITLE
convert `array-like-objects` to `array`

### ISSUE THREAD

**Issue by davidcheung** [strongloop/strong-remoting#376]
**what**
on the roadmap of qs, they have the plans of changing default arrayLimit to 0, which is what express uses to build the query object

**what it will mean for us**
meaning queries in `filter[where][or][0][id]=1` format will be converted to objects instead of array,  currently qs(default settings) converts array-like-objects under 20 items into arrays (which becomes very hard to troubleshoot when your query with 20 item works, and 21st item then it breaks)

**possible solution**
perhaps we need our own way of dealing with this on the query parsing level. ideally something that is configurable that user can decide whether they want their `array-like-objects` to be converted to `arrays` so its more predictable

related https://github.com/strongloop/loopback/issues/2824
https://github.com/ljharb/qs/issues/107

**Comment by doublemarked** [comment]
I agree that it seems more appropriate to deal with this in strong-remoting than in DataAccessObject._coerce.

**Comment by bajtos** [comment]
With the release of LoopBack 4.0 GA (see the [announcement](https://strongloop.com/strongblog/loopback-4-ga)), this module has entered Active LTS mode and no longer accepts new features (see our [LTS policy](https://loopback.io/doc/en/contrib/Long-term-support.html)).
