### ISSUE TITLE
Validate nested properties of object arguments

### ISSUE THREAD

**Issue by Overdrivr** [strongloop/strong-remoting#387]
[Does validation works on nested `args` objects](http://stackoverflow.com/questions/40803541/loopback-remote-method-parameter-validation) ?

With a remote method configured like this for instance

```
 WebuserModel.remoteMethod('overLogin',  {
      description: "Performs a Webuser's login to the system",
      accepts: [
        {
          arg: 'credentials', type: {
            "username": { type: "string", required:true },
            "password": { type: "string", required: true }
          },
          http: {source: 'body'},
          required: true
        },
      ],
      returns: {arg: 'accesToken', type: "object", root: true},
      http: {path: '/login', verb: 'post'}
    }
```

If not maybe it should be mentioned in the [docs](https://loopback.io/doc/en/lb2/Remote-methods.html#http-mapping-of-input-arguments)

**Comment by request-eduardo** [comment]
Looking forward for this answer too

**Comment by bajtos** [comment]
Hi, I am afraid strong-remoting does not validate properties of object types right now.

**Comment by bajtos** [comment]
With the release of LoopBack 4.0 GA (see the [announcement](https://strongloop.com/strongblog/loopback-4-ga)), this module has entered Active LTS mode and no longer accepts new features (see our [LTS policy](https://loopback.io/doc/en/contrib/Long-term-support.html)).
