### ISSUE TITLE
Remote method does not work if arg value is called `data`

### ISSUE THREAD

**Issue by Johnyjsrs** [strongloop/strong-remoting#388]
default value is not get in for this example:
```
'accepts': [
{
'arg': 'data',
'description': 'my description',
'type': 'object',
'default': '{"name": "foo"}',
'required': true,
'http': { 'source': 'body' },
},
],
```

**Comment by bajtos** [comment]
@Johnyjsrs Could you please provide is with a runnable code we can use to reproduce the problem on our machines? For example a failing unit-test for strong-remoting, or a simple LoopBack app per our [bug  reporting instructions](http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report)

**Comment by bajtos** [comment]
Closing the issue as abandoned.
