### ISSUE TITLE
Sending multiple `_format` values crashes

### ISSUE THREAD

**Issue by STRML** [strongloop/strong-remoting#396]
- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

When sending a request like `GET /api/v1/foo?_format=xml&_format=json` crashes due to [this line](https://github.com/strongloop/strong-remoting/blob/14a03ccfd9a9b4210d3e68e9a87ed76e07948b6e/lib/http-context.js#L554) which assumes that `_format` is a string. It could be an array.

**Comment by bajtos** [comment]
Thank you for reporting the problem. Would you like to contribute the fix yourself?

What is your expected solution: Should we reject requests with `_format` that's not a string? Should we pick the first `_format` item that is supported by the server, like we are doing with `Accepts` header? Something else?
