### ISSUE TITLE
can we update dependencies of sse@0.0.6 to 0.0.7?

### ISSUE THREAD

**Issue by smartmouse** [strongloop/strong-remoting#436]
# Description/Steps to reproduce

sse@0.0.6 depends on options@latest
This is not good for production.
sse@0.0.7 recently updated to fix the dependency to options@0.0.6 instead of latest

Also we ran into an issue of resolving @latest in the build between different npm versions.
**npm 5.x**

dc60server:apiconnect smartmouse$ npm ls options@latest
```

├─┬ apiconnect-cli-loopback@2.6.6
│ └─┬ loopback-workspace@3.42.0
│   └─┬ loopback@2.39.0
│     └─┬ strong-remoting@2.34.0
│       └─┬ sse@0.0.6
│         └── options@0.0.6 
```

dc60server:apiconnect smartmouse$ npm ls options@latest

**npm 3.10.10**

```
npm ls options@latest

├─┬ apiconnect-cli-loopback@2.6.6
│ └─┬ loopback-workspace@3.42.0
│   └─┬ loopback@2.39.0
│     └─┬ strong-remoting@2.34.0
│       └─┬ sse@0.0.6
│         └── options@0.0.6  invalid

```

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by bajtos** [comment]
@smartmouse is this still relevant? Would you mind to contribute this upgrade yourself and open a pull request?

**Comment by bajtos** [comment]
We are using `sse@0.0.8` now.
