### ISSUE TITLE
typo: HttpContext.prototype.resolveReponseOperation

### ISSUE THREAD

**Issue by alert83** [strongloop/strong-remoting#440]
# Description/Steps to reproduce

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by raymondfeng** [comment]
@alert83 Thank you for reporting it. Would you like to submit a pull request?

**Comment by alert83** [comment]
you are welcome. I do not have experience in submiting a pull request

**Comment by bajtos** [comment]
@alert83 what a great learning opportunity! Here is a detailed step-by-step guide teaching how to send the first pull request: https://www.nearform.com/blog/getting-into-open-source-for-the-first-time
