### ISSUE TITLE
Wrong prop is used for pipe source?

### ISSUE THREAD

**Issue by killmenot** [strongloop/strong-remoting#460]
Hi, I think switch statement should use `pipeSrc` not `pipeDest`, isn't it?

https://github.com/strongloop/strong-remoting/blob/f6ef3aedce857709e89efb35800465bd34481d40/lib/http-context.js#L285-L289

**Comment by bajtos** [comment]
Makes sense.

Would you like to contribute the fix yourself? Just make sure to include a test to verify the change.
