### ISSUE TITLE
Possibly wrong @property definitions in documentation? 

### ISSUE THREAD

**Issue by pure180** [strongloop/strong-remoting#462]
Currently I'm writing some type definitions for this plugin and I found out that there are some wrong declared Prams, please correct me if I'm wrong.

https://github.com/strongloop/strong-remoting/blob/33fbd72fb46035f707c3c62dce6b36ab075fb61e/lib/shared-method.js#L40 should be Object?

https://github.com/strongloop/strong-remoting/blob/33fbd72fb46035f707c3c62dce6b36ab075fb61e/lib/shared-method.js#L41 should be Boolean?

https://github.com/strongloop/strong-remoting/blob/33fbd72fb46035f707c3c62dce6b36ab075fb61e/lib/shared-method.js#L182 should be String?

If i Find more I'll let you know.

**Comment by bajtos** [comment]
@pure180 thank you for opening this issue, I think your analysis is correct. Would you like to open a pull request to improve our documentation?
