### ISSUE TITLE
Server stream not closed if requested as application/json 

### ISSUE THREAD

**Issue by Wizarth** [strongloop/strong-remoting#482]
I've provided a unit test at: https://github.com/Wizarth/strong-remoting/tree/json-zombie-streams

## Steps to reproduce

Run the unit test in stream.js: 
> a function returning a ReadableStream  
>> an http client requesting a stream as JSON  
>>> should close server stream on client disconnect

This case is caused by HttpInvocation.prototype.createRequest setting json: true , which is then used in HttpInvocation.prototype.invoke , when methodReturnsStream is true.

Previously reported as Loopback issue https://github.com/strongloop/loopback/issues/4317 , which includes use of loopback-sandbox to replicate the issue.

## Steps to reproduce

Using the remote, connecting to change-stream creates an observer on the model that is never removed.

With this sandbox:
In separate shells

    NODE_ENV=backend node server/server.js
    NODE_ENV=frontend node server/server.js
    node test.js

## Current Behavior

backend is on localhost:3000
frontend is on localhost:3010

backend is using in-memory db for Test model.
frontend is using loopback-connector-remote, connecting to backend, for Test model.

server.js has a once per second check for the # of _observers['after save'] on the Test model.

test.js runs two tests. The first connects 100 times to http://localhost:3000/api/Tests/change-stream (using request). After ten seconds, these requests are aborted.

During this time, the backend loopback instance reports 100 after save observers. When the requests are disconnected, the number of observers drops to zero.

In the second test, 100 connections to http://localhost:3010/api/Tests/change-stream are created (the frontend). After ten seconds, these requests are aborted.

During this time, the backend loopback instance reports 100 after save observers. When the requests are disconnected, the number of observers does not drop.

Terminating the frontend instance does not cause the number of observers to drop.

## Expected Behavior

Disconnecting the HTTP request should remove the observer.

## Link to reproduction sandbox

https://github.com/Wizarth/loopback-sandbox/tree/change-stream_Observer

## Additional information

Node version: 

- win32 x64 10.16.0
- linux x64 8.14.0

Sandbox:
loopback-sandbox@1.0.0 C:\...\loopback-sandbox
+-- loopback@3.26.0
+-- loopback-boot@3.3.1
+-- loopback-component-explorer@6.4.0
+-- loopback-connector-remote@3.4.1
+-- loopback-connector-rest@3.6.0

We are using a setup where front-end Loopback servers are communicating to a single back-end Loopback server. The back-end server is primarily to centralize event handling, while the front end is doing per-session logic as much as possible.  The front-end is connected to the backend using loopback-connector-remote (which uses strong-remoting).

The structure is NGINX -> front-end Loopback <> back end Loopback <> Various internal services.

We've set up a web app that uses the JS EventStream class to connect to the persisted models change-stream endpoint. What we're finding is that over time, the CPU usage of the back end Loopback increases every time the persisted model is updated. This CPU usage increases up to seeing multiple seconds of 100% processor usage by this process, which has all sorts of knock on bad effects.

By adding logging to loopback-datasource-juggler / lib/observer.js , we're seeing that once every two minutes, on the back-end server, a new observe 'after save' handler is attached, without any corresponding call to removeObserver . (change-stream sends an end event after two minutes of inactivity, which our client responds to by re-connecting.)

We've also found that connecting NGINX to the back end Loopback for the specific change-stream API doesn't show this behavior.

The provided sandbox fork is an artificial test case of connecting 100 clients at once, to simulate the connections created over time.

**Comment by emonddr** [comment]
@Wizarth , thank you for providing the detailed explanation and the sandbox link.

**Comment by agnes512** [comment]
@jannyHou could you take a look at the PR? thank you!

**Comment by jannyHou** [comment]
looking, will reply asap
